version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: library/php
    container_name: heic_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www

